### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mikay1337** [ReimarPB/GrowtopiaPacketReader#1]
I Have a Problem when run this program

Error: unable to intercept function at 00007FF7E14E1440; please file a bug
    at value (frida/runtime/core.js:316)
    at <eval> (/growtopia.js:22)

**Comment by ReimarPB** [comment]
This program was made for an older version of Growtopia (3.4 something I think). Apparently the memory addresses for the relevant functions change for every update meaning it's useless unless I find the new addresses (which can be a pain). Sorry about that.

**Comment by ReimarPB** [comment]
I have now updated it so that it should work in the current version, and probably a lot of future versions as well.
