### ISSUE TITLE
Failed to spawn error

### ISSUE THREAD

**Issue by Furkan125** [ReimarPB/GrowtopiaPacketReader#2]
Hi, i got this error when i try to run code: Failed to spawn: unable to find process with name 'Growtopia.exe'

btw its works on latest version of growtopia ?

**Comment by ReimarPB** [comment]
You must be running PowerShell as an administrator, or else it won't work.

And no, it doesn't work anyway because it's outdated. I might see if I can get it updated, but I won't promise anything.

**Comment by ReimarPB** [comment]
I actually got it to work on the newest version now. Just download the new file and do the same thing in PowerShell admin mode and it should work perfectly.

**Comment by ReimarPB** [comment]
UPDATE: I just tested it on the newest version and got banned.. Can't tell if the script is causing it but be careful. I'm adding a warning to the readme.

**Comment by Furkan125** [comment]
Hello, first of all thanks for your replies. It doesn't matter if I'm banned or not, I can unban, but I'll still try using Ban Bypass, I also have a request from you, can you teach me how to adapt the program to the latest version? So you don't have to deal with every new version.

**Comment by ReimarPB** [comment]
There's no need to, with the new file it'll automatically adapt to new versions of Growtopia.

**Comment by Furkan125** [comment]
Wow, really? Thank you so much.

**Comment by Furkan125** [comment]
Hi, the code worked fine. By the way, it does not cause you to be banned while there is Ban Bypass, and if you want to use it, the opcode of Ban Bypass for the latest version is "Growtopia.exe"+336AF4.

**Comment by ReimarPB** [comment]
Ah nice, thank you!
